pipeline {
    agent {
        label 'DockerAgents'
    }
    environment {
        SONARQUBETOKEN = credentials('sonar-qube-token')
    }
    options {
        disableConcurrentBuilds()
    }
    stages {
        stage('Run CLI Command') {
            steps {
                script {
                    println "Running build"
                }
            }
        }
        stage('Maven Package') {
            steps {
                mavenPackage()
            }
        }
        stage('Sonar') {
            steps {
                sh "mvn sonar:sonar \
                      -Dsonar.projectKey=com.aeontree.springci \
                      -Dsonar.host.url=http://sonarqube:9000 \
                      -Dsonar.login=$SONARQUBETOKEN"
            }
        }
        stage('Publish') {
            steps {
                nexusPublisher nexusInstanceId: 'nexus', nexusRepositoryId: 'localartifacts', packages: [[$class: 'MavenPackage', mavenAssetList: [[classifier: '', extension: '', filePath: 'target/springci-0.0.1-SNAPSHOT.jar']], mavenCoordinate: [artifactId: 'springci', groupId: 'com.andreilorin', packaging: 'jar', version: '0.0.1-SNAPSHOT']]]
            }
        }
    }
    post {
        always {
            cleanWs()
        }
    }
}

def mavenPackage() {
    def maven_build="mvn clean package"
    sh(script: maven_build)
}