pipeline {
    agent {
        docker {
            image 'dockeragentmvn:latest'
            label 'DockerAgents'
            args '-v maven_repository:/root/.m2'
        }
    }
    options {
        disableConcurrentBuilds()
    }
    stages {
        stage('Run CLI Command') {
            steps {
                script {
                    println "Running build"
                }
            }
        }
        stage('Maven Package') {
            steps {
                mavenPackage()
            }
        }
        stage('List Maven Repository Contents') {
            steps {
                sh 'ls /root/.m2'
            }
        }
    }
}

def mavenPackage() {
    def maven_build="mvn clean package"
    sh(script: maven_build)
}