pipeline {
    agent {
        label 'DockerAgents'
    }
    options {
        disableConcurrentBuilds()
    }
    stages {
        stage('Run CLI Command') {
            steps {
                script {
                    println "Running build"
                }
            }
        }
        stage('Maven Package') {
            steps {
                mavenPackage()
            }
        }
        stage('Sonar') {
            steps {
                sh "mvn sonar:sonar -Dsonar.host.url=http://localhost:13004"
            }
        }
    }
    post {
        always {
            cleanWs()
        }
    }
}

def mavenPackage() {
    def maven_build="mvn clean package"
    sh(script: maven_build)
}